[package]
name = "terminal_notes"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
clap = { version = "4.5.9", features = ["derive"] }
home = "0.5.9"
log = "0.4.22"
simple-logging = "2.0.2"
termion = "1"
toml = "0.8.19"
